version: '3.8'

services:
  recept-ebook-app:
    image: jkaninda/laravel-php-fpm:8.2
    container_name: recept-ebook-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - recept-ebook-net

  mysql:
    image: mysql:8.0
    container_name: recept-ebook-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - recept-ebook-net

  redis:
    image: redis:latest
    container_name: recept-ebook-redis
    networks:
      - recept-ebook-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: recept-ebook-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - UPLOAD_LIMIT=1G
    ports:
      - 8081:80
    networks:
      - recept-ebook-net

  nginx-server:
     image: jkaninda/nginx-fpm:alpine
     container_name: nginx-server
     restart: unless-stopped
     ports:
      - 80:80
     volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
     environment:
       - DOCUMENT_ROOT=/var/www/html/public
       - CLIENT_MAX_BODY_SIZE=20M
       - PHP_FPM_HOST=recept-ebook-app:9000
     networks:
      - recept-ebook-net
networks:
  recept-ebook-net:
      driver: bridge

